### PR TITLE
[OPS-8346] inline php_stream_parse_fopen_modes on php < 7.3

### PR DESCRIPTION
**Pull request by jpackagejasonc**

### CODE REVIEW

**Comment by jpackagejasonc** [comment]
this PR is an attempt to address the following warning:
```
shadow.c: In function 'shadow_stream_opener':
shadow.c:782:5: warning: implicit declaration of function 'php_stream_parse_fopen_modes'; did you mean 'php_stream_free_enclosed'? [-Wimplicit-function-declaration]
```

**Comment by morozov** [comment]
@jpackagejasonc I'm not that much familiar with PHP internals and shadow to provide any feedback. If there's a missing header in PHP, could you identify an existing bug or file a new one so that we could track it? If it's not a bug, then there might be a different way to solve this issue.

Could you please also check if https://github.com/php/php-src/commit/98416a37f36825d2179ca26c25048db83cb1c22c is relevant?

**Comment by jpackagejasonc** [comment]
@morozov I do think https://github.com/php/php-src/commit/98416a37f36825d2179ca26c25048db83cb1c22c is relevant which is why I kept my ifdef to 7.3.0 and lower. for internal bug links I believe this is related to OPS-8346 and OPS-8349, which both originate from ITR 103866

**Comment by jpackagejasonc** [comment]
@alex-vlasov I think Sergey has deferred to you on this one

**Comment by jpackagejasonc** [comment]
actually I think I might be muddying the discussion waters here with my potential solution. I've raised TR-19811 for this and a couple other problems, will let whoever gets assigned that one decide the proper solve.

**Pull request closed without merging**
